### ISSUE TITLE
Setting UVCC autoWhiteBalance to 0 Getting LIBUSB_ERROR_IO

### ISSUE THREAD

**Issue by GaganMeesala** [joelpurra/uvcc#2] opened 2019-07-24 11:54 UTC
`sudo uvcc devices`

```
Optical Mouse [ vId: 0x458  / pId: 0x3a  ]
USB Keyboard [ vId: 0x4d9  / pId: 0x1702  ]
EHCI Host Controller [ vId: 0x1d6b  / pId: 0x2  ]
EHCI Host Controller [ vId: 0x1d6b  / pId: 0x2  ]
USB 2.0 Camera [ vId: 0xc45  / pId: 0x6366  ]

```
`sudo uvcc --vendor 0xc45 --product 0x6366 set autoWhiteBalance 0`

`Error: LIBUSB_ERROR_IO
`
![Screenshot from 2019-07-24 17-18-41](https://user-images.githubusercontent.com/10542233/61791503-cbf86a00-ae37-11e9-8082-524c933631b9.png)

**Comment by joelpurra** [comment] 2019-08-09 11:34
@GaganMeesala: I can confirm the problem -- am also getting `LIBUSB_ERROR_IO` on ubuntu. The same webcam works on macOS without any issue. Looks like the problem isn't in `uvcc` though, but in upstream code.

Noticed that you opened the same issue in `uvc-control`; closing in favor of that issue.

- https://github.com/makenai/node-uvc-control/issues/58

**Closed by joelpurra** 2019-08-09 11:34 UTC
